---
- hosts: localhost
  gather_facts: false
  vars:
    input: &input
      hostname:       "{{ PRI_CLU }}"
      username:       "{{ PRI_CLU_USER }}"
      password:       "{{ PRI_CLU_PASS }}"
      https:          true
      validate_certs: false
# root_volume_aggregate currently not supported with REST
#      use_rest:       Always
  vars_files:
    - global.vars
  collections:
    - netapp.ontap

  tasks:
  - name: Create primary SVM
    na_ontap_svm:
      state:                 present
      name:                  "{{ PRI_SVM }}"
      root_volume_aggregate: "{{ PRI_AGGR }}"
      comment:               Created with Ansible
      <<: *input

  - name: Create management interface on primary SVM
    na_ontap_interface:
      state:                 present
      interface_name:        "{{ PRI_SVM }}"
      vserver:               "{{ PRI_SVM }}"
      address:               "{{ PRI_SVM_IP }}"
      netmask:               "{{ PRI_SVM_NETMASK }}"
      home_node:             "{{ PRI_CLU_NODE1 }}"
      home_port:             "{{ PRI_MGMT_PORT }}"
      service_policy:        default-management
      role:                  data
      <<: *input

  - name: Create DNS on primary SVM
    na_ontap_dns:
      state:                 present
      vserver:               "{{ PRI_SVM }}"
      domains:               "{{ PRI_DOMAIN }}"
      nameservers:           "{{ PRI_DNS1 }}"
      <<: *input

  - name: Create CIFS interface on primary SVM
    na_ontap_interface:
      state:                 present
      interface_name:        "{{ PRI_SVM }}_cifs_01"
      vserver:               "{{ PRI_SVM }}"
      address:               "{{ PRI_SVM_CIFS_IP }}"
      netmask:               "{{ PRI_SVM_CIFS_NETMASK }}"
      home_node:             "{{ PRI_CLU_NODE1 }}"
      home_port:             "{{ PRI_DATA_PORT }}"
      role:                  data
      protocols:             cifs
      <<: *input

  - name: Create CIFS server on primary SVM
    na_ontap_cifs_server:
      state:                 present
      service_state:         started
      name:                  "{{ PRI_SVM }}"
      vserver:               "{{ PRI_SVM }}"
      domain:                "{{ PRI_AD_DOMAIN }}"
      admin_user_name:       "{{ PRI_AD_USER }}"
      admin_password:        "{{ PRI_AD_PASS }}"
      <<: *input

  - name: Create volume on primary SVM
    na_ontap_volume:
      state:                 present
      name:                  "{{ PRI_SVM }}_cifs_01"
      vserver:               "{{ PRI_SVM }}"
      size:                  "{{ VOL_SIZE }}"
      size_unit:             b
      aggregate_name:        "{{ PRI_AGGR }}"
      comment:               Created with Ansible
      space_guarantee:       volume
      policy:                default
      junction_path:         "/{{ PRI_SVM }}_cifs_01"
      volume_security_style: ntfs
      <<: *input

  - name: Create CIFS share on primary SVM
    na_ontap_cifs:
      state:                 present
      share_name:            "jenkins"
      vserver:               "{{ PRI_SVM }}"
      path:                  "/{{ PRI_SVM }}_cifs_01/"
      <<: *input